// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"

	monitor "github.com/opsway-io/backend/internal/monitor"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CountByTeamID provides a mock function with given fields: ctx, teamID
func (_m *Repository) CountByTeamID(ctx context.Context, teamID uint) (int64, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeamID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Repository) Create(ctx context.Context, _a1 *entities.Monitor) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Monitor) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, teamID, monitorID
func (_m *Repository) Delete(ctx context.Context, teamID uint, monitorID uint) error {
	ret := _m.Called(ctx, teamID, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, teamID, monitorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMonitorAndSettingsByTeamIDAndID provides a mock function with given fields: ctx, teamID, monitorID
func (_m *Repository) GetMonitorAndSettingsByTeamIDAndID(ctx context.Context, teamID uint, monitorID uint) (*entities.Monitor, error) {
	ret := _m.Called(ctx, teamID, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitorAndSettingsByTeamIDAndID")
	}

	var r0 *entities.Monitor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*entities.Monitor, error)); ok {
		return rf(ctx, teamID, monitorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entities.Monitor); ok {
		r0 = rf(ctx, teamID, monitorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Monitor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, teamID, monitorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonitorAssertionByID provides a mock function with given fields: ctx, monitorAssertionID
func (_m *Repository) GetMonitorAssertionByID(ctx context.Context, monitorAssertionID uint) (*entities.MonitorAssertion, error) {
	ret := _m.Called(ctx, monitorAssertionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitorAssertionByID")
	}

	var r0 *entities.MonitorAssertion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.MonitorAssertion, error)); ok {
		return rf(ctx, monitorAssertionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.MonitorAssertion); ok {
		r0 = rf(ctx, monitorAssertionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.MonitorAssertion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, monitorAssertionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonitorsAndIncidentsByTeamID provides a mock function with given fields: ctx, teamID
func (_m *Repository) GetMonitorsAndIncidentsByTeamID(ctx context.Context, teamID uint) (*[]entities.Monitor, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitorsAndIncidentsByTeamID")
	}

	var r0 *[]entities.Monitor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*[]entities.Monitor, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *[]entities.Monitor); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Monitor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonitorsAndSettingsByTeamID provides a mock function with given fields: ctx, teamID, offset, limit, query
func (_m *Repository) GetMonitorsAndSettingsByTeamID(ctx context.Context, teamID uint, offset *int, limit *int, query *string) (*[]monitor.MonitorWithTotalCount, error) {
	ret := _m.Called(ctx, teamID, offset, limit, query)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitorsAndSettingsByTeamID")
	}

	var r0 *[]monitor.MonitorWithTotalCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int, *string) (*[]monitor.MonitorWithTotalCount, error)); ok {
		return rf(ctx, teamID, offset, limit, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int, *string) *[]monitor.MonitorWithTotalCount); ok {
		r0 = rf(ctx, teamID, offset, limit, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]monitor.MonitorWithTotalCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *int, *int, *string) error); ok {
		r1 = rf(ctx, teamID, offset, limit, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonitorsByStates provides a mock function with given fields: ctx, states
func (_m *Repository) GetMonitorsByStates(ctx context.Context, states []entities.MonitorState) (*[]entities.Monitor, error) {
	ret := _m.Called(ctx, states)

	if len(ret) == 0 {
		panic("no return value specified for GetMonitorsByStates")
	}

	var r0 *[]entities.Monitor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.MonitorState) (*[]entities.Monitor, error)); ok {
		return rf(ctx, states)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []entities.MonitorState) *[]entities.Monitor); ok {
		r0 = rf(ctx, states)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Monitor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []entities.MonitorState) error); ok {
		r1 = rf(ctx, states)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetState provides a mock function with given fields: ctx, teamID, monitorID, state
func (_m *Repository) SetState(ctx context.Context, teamID uint, monitorID uint, state entities.MonitorState) error {
	ret := _m.Called(ctx, teamID, monitorID, state)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, entities.MonitorState) error); ok {
		r0 = rf(ctx, teamID, monitorID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, teamID, monitorID, _a3
func (_m *Repository) Update(ctx context.Context, teamID uint, monitorID uint, _a3 *entities.Monitor) error {
	ret := _m.Called(ctx, teamID, monitorID, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *entities.Monitor) error); ok {
		r0 = rf(ctx, teamID, monitorID, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
