log:
  level: debug
  format: text

rest:
  port: 8001

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 24h
  refresh_expires_in: 720h 

postgres:
  dsn: "host=localhost user=postgres password=pass dbname=opsway port=5432 sslmode=disable" 
  debug: true

clickhouse:
  dsn: clickhouse+native://default:@localhost:9000/opsway
  debug: true

redis:
  host: redis
  port: 6379
  db: 0

email:
  sender_name: "opsway"
  sender_email: "no-reply@opsway.io"
  sendgrid_api_key: "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"

object_storage:
  endpoint_url: "http://localhost:9001"
  access_key: "guest"
  secret_key: "supersecret"
  region: "eu-central-1"
  public_url: "http://localhost:9001"

prober:
  concurrency: 1
  