log:
  level: debug
  format: json

rest:
  port: 8001

postgres:
  dsn: "host=localhost user=admin password=admin dbname=opsway port=5432 sslmode=disable"
  debug: true

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 24h
  refresh_expires_in: 720h

clickhouse:
  dsn: "clickhouse://default:@localhost:9000/opsway?dial_timeout=200ms&max_execution_time=60"
  debug: true

asynq:
  host: localhost
  port: 6379
