log:
  level: debug
  format: json

rest:
  port: 8001

postgres:
  dsn: "host=localhost user=admin password=admin dbname=opsway port=5432 sslmode=disable"
  debug: false

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 5m
  refresh_expires_in: 720h

clickhouse:
  dsn: "clickhouse://default:@localhost:9000/default?dial_timeout=200ms&max_execution_time=60"
  debug: true

asynq:
  host: localhost
  port: 6379

redis:
  host: localhost
  port: 6379
  user: ""
  password: ""

notification:
  email:
    debug: true
    sender_name: "opsway"
    sender_email: "no-reply@opsway.io"
    sendgrid_api_key: ""

object_storage:
  endpoint_url: "http://localhost:9001"
  access_key: "guest"
  secret_key: "guest"
  region: "eu-central-1"