log:
  level: debug
  format: text

rest:
  port: 8001

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 1h
  refresh_expires_in: 720h
  cookie_domain: localhost
  cookie_secure: false

postgres:
  dsn: "host=postgres user=postgres password=pass dbname=opsway port=5432 sslmode=disable"
  debug: true

clickhouse:
  dsn: clickhouse+native://default:@ch_server:9000/opsway
  debug: true

redis:
  host: redis
  port: 6379
  db: 0

email:
  debug: true
  sender_name: "opsway"
  sender_email: "no-reply@opsway.io"

object_storage:
  endpoint_url: "http://storage:9001"
  access_key: "guest"
  secret_key: "supersecret"
  region: "eu-central-1"
  public_url: "http://localhost:9001"

prober:
  concurrency: 1

team:
  invitation_secret: supersecret
  application_url: http://localhost:5173

stripe:
  secret_key: "test"
  endpoint_secret: "test"