log:
  level: info
  format: text

rest:
  port: 8005

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 24h
  refresh_expires_in: 720h 
  cookie_domain: localhost
  cookie_secure: false

postgres:
  dsn: "host=localhost user=postgres password=pass dbname=opsway port=5432 sslmode=disable" 
  debug: false

clickhouse:
  dsn: clickhouse+native://default:@localhost:9000/opsway
  debug: true

redis:
  host: localhost
  port: 6379
  db: 0

email:
  debug: true
  sender_name: "opsway"
  sender_email: "no-reply@opsway.io"

object_storage:
  endpoint_url: "http://localhost:9001"
  access_key: "guest"
  secret_key: "supersecret"
  region: "eu-central-1"
  public_url: "http://localhost:9001"

team:
  invitation_secret: supersecret
  application_url: http://localhost:5173

prober:
  concurrency: 1

stripe:
  publishable_key: pk_test_51NjhPuAAd26uMXu2mDsC5CrJzCokmFCMDEiyZFGanTQAy2exlztxyuLDpg2TXC26LK8j9wqnACLAAwEyWS0AJ4r500U1rDn672
  secret_key: sk_test_51NjhPuAAd26uMXu2QkGAVDTZDLYGRQB2oxqWkZfH6j4XUOIg2HBOOKB5wRL25vOo0VkpfjnxXnP0aZ8NZqvqex3N00JZU6eD2H
  webhook_secret: "whsec_4665482442d698095ed89e386c0069beb54a1ba141a371edd4e8e0c5126d7568"
  domain: http://localhost:5173
  