log:
  level: info
  format: text
database:
  dsn: books:secret@tcp(localhost:3306)/books?charset=utf8&parseTime=True
http:
  port: 8080
grpc:
  port: 50051
nats:
  dsn: nats://localhost:4222
  cluster: example-cluster
  consumerID: example-consumer
  subject: example-subject
  queueGroup: example-queue-group
  durableName: example-durable-name
  maxInFlight: 10
  ackWaitTimeout: 10s
prometheus:
  enabled: true
  port: 9090
  path: /metrics
health:
  port: 8081
