log:
  level: debug
  format: json

rest:
  port: 8080

postgres:
  dsn: "host=localhost user=admin password=admin dbname=opsway port=5432 sslmode=disable"
  debug: true

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 24h
  refresh_expires_in: 720h

influxdb:
  host: localhost
  port: 8086
  token: c2b67Z10xdccn0oWmN1d4SsBdCaU7RCDuesd0R8iSR-9pHSGfbvkTjlFCN3HONydaLjjmL82bS-sQQl2s1z6uw==

asynq:
  host: localhost
  port: 6379
