log:
  level: debug
  format: text

rest:
  port: 8001

postgres:
  dsn: "host=postgres user=admin password=admin dbname=opsway port=5432 sslmode=disable"
  debug: true

authentication:
  secret: "secret"
  audience: "https://opsway.io"
  issuer: "opsway.io"
  expires_in: 24h
  refresh_expires_in: 720h 

influxdb:
  host: influxdb
  port: 8086
  token: c2b67Z10xdccn0oWmN1d4SsBdCaU7RCDuesd0R8iSR-9pHSGfbvkTjlFCN3HONydaLjjmL82bS-sQQl2s1z6uw==

clickhouse:
  dsn: "host=clickhouse user=default password= dbname=opsway port=8123 sslmode=disable"
  debug: true

asynq:
  host: localhost
  port: 6379