version: '3.1'


services:
  postgres:
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.1
    command: keydb-server /etc/keydb/keydb.conf --server-threads 2
    ports:
      - 6379:6379
    restart: unless-stopped

  influxdb:
    image: influxdb:2.3
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-prompass}
    ports:
      - 8086:8086
    volumes:
      - /tmp/influxdb2:/var/lib/influxdb2:rw

  # api:
  #   build: .
  #   ports:
  #     - 8000:8000
  #   restart: unless-stopped
  #   depends_on:
  #     - keydb
  #     - database

  prober:
    build: .
    command: sub
    restart: unless-stopped
    depends_on:
      - keydb
      - database
