version: '3.1'

services:
  postgres:
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: opsway
    volumes:
      - ./data/postgres:/var/lib/posgresql/data
    ports:
      - 5432:5432

  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.1
    restart: unless-stopped
    command: keydb-server /etc/keydb/keydb.conf --server-threads 2
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./data/redisinsight:/db 

  influxdb:
    image: influxdb:2.3-alpine
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./data/influx:/var/lib/influxdb2:rw

  # api:
  #   build: .
  #   command: api
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./config.compose.yaml:/app/config.yaml:r
  #   depends_on:
  #     - postgres
  #     - keydb
  #     - influxdb
  

  # prober:
  #   build: .
  #   restart: unless-stopped
  #   command: prober
  #   depends_on:
  #     - keydb
  #     - influxdb