version: '3.1'
services:
  postgres:
    image: 'postgres:14.4-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: opsway
    volumes:
      - './data/postgres:/var/lib/posgresql/data'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:6.2-alpine'
    ports:
      - '6379:6379'
    command: redis-server
  ch_server:
    image: clickhouse/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - './data/clickhouse:/var/lib/clickhouse'
  ch_client:
    image: clickhouse/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
  s3:
    image: minio/minio
    ports:
      - '9001:9001'
      - '5566:5566'
    volumes:
      - './data/minio:/data'
    environment:
      MINIO_ACCESS_KEY: guest
      MINIO_SECRET_KEY: supersecret
      
    command: 'server --address 0.0.0.0:9001 --console-address 0.0.0.0:5566 /data'
