version: '3.1'

services:
  # database:
  #   image: mysql:8.0.23
  #   environment:
  #     MYSQL_DATABASE: 'books'
  #     MYSQL_USER: 'books'
  #     MYSQL_PASSWORD: 'secret'
  #     MYSQL_RANDOM_ROOT_PASSWORD: 'true'
  #   ports:
  #     - 3306:3306

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports: 
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
