version: '3.1'

services:
  # database:
  #   image: mysql:8.0.23
  #   environment:
  #     MYSQL_DATABASE: 'books'
  #     MYSQL_USER: 'books'
  #     MYSQL_PASSWORD: 'secret'
  #     MYSQL_RANDOM_ROOT_PASSWORD: 'true'
  #   ports:
  #     - 3306:3306

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports: 
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  keydb:
    image: eqalpha/keydb:x86_64_v6.2.2
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    ports:
      - 6379:6379
    restart: unless-stopped

  influxdb:
    image: influxdb:2.3
    environment:
      - INFLUXDB_ADMIN_ENABLED=true 
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-prompass}
    ports:
      - 8086:8086
    volumes:
      - /tmp/influxdb2:/var/lib/influxdb2:rw