// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CountByTeamID provides a mock function with given fields: ctx, teamID
func (_m *Service) CountByTeamID(ctx context.Context, teamID uint) (int64, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTeamID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, statusPage
func (_m *Service) Create(ctx context.Context, statusPage *entities.StatusPage) error {
	ret := _m.Called(ctx, statusPage)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.StatusPage) error); ok {
		r0 = rf(ctx, statusPage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, teamID
func (_m *Service) Delete(ctx context.Context, id uint, teamID uint) error {
	ret := _m.Called(ctx, id, teamID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByDomain provides a mock function with given fields: ctx, domain
func (_m *Service) GetByDomain(ctx context.Context, domain string) (*entities.StatusPage, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetByDomain")
	}

	var r0 *entities.StatusPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.StatusPage, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.StatusPage); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.StatusPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDAndTeamID provides a mock function with given fields: ctx, id, teamID
func (_m *Service) GetByIDAndTeamID(ctx context.Context, id uint, teamID uint) (*entities.StatusPage, error) {
	ret := _m.Called(ctx, id, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndTeamID")
	}

	var r0 *entities.StatusPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*entities.StatusPage, error)); ok {
		return rf(ctx, id, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entities.StatusPage); ok {
		r0 = rf(ctx, id, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.StatusPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, id, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeamID provides a mock function with given fields: ctx, teamID
func (_m *Service) GetByTeamID(ctx context.Context, teamID uint) ([]*entities.StatusPage, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamID")
	}

	var r0 []*entities.StatusPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*entities.StatusPage, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*entities.StatusPage); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.StatusPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriberByToken provides a mock function with given fields: ctx, token
func (_m *Service) GetSubscriberByToken(ctx context.Context, token string) (*entities.StatusPageSubscriber, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriberByToken")
	}

	var r0 *entities.StatusPageSubscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.StatusPageSubscriber, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.StatusPageSubscriber); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.StatusPageSubscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVerifiedSubscribers provides a mock function with given fields: ctx, statusPageID
func (_m *Service) GetVerifiedSubscribers(ctx context.Context, statusPageID uint) ([]entities.StatusPageSubscriber, error) {
	ret := _m.Called(ctx, statusPageID)

	if len(ret) == 0 {
		panic("no return value specified for GetVerifiedSubscribers")
	}

	var r0 []entities.StatusPageSubscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entities.StatusPageSubscriber, error)); ok {
		return rf(ctx, statusPageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.StatusPageSubscriber); ok {
		r0 = rf(ctx, statusPageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.StatusPageSubscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, statusPageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReplaceMonitors provides a mock function with given fields: ctx, statusPage, monitors
func (_m *Service) ReplaceMonitors(ctx context.Context, statusPage *entities.StatusPage, monitors []entities.Monitor) error {
	ret := _m.Called(ctx, statusPage, monitors)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceMonitors")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.StatusPage, []entities.Monitor) error); ok {
		r0 = rf(ctx, statusPage, monitors)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, statusPageID, email, token
func (_m *Service) Subscribe(ctx context.Context, statusPageID uint, email string, token string) error {
	ret := _m.Called(ctx, statusPageID, email, token)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, statusPageID, email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Unsubscribe provides a mock function with given fields: ctx, token
func (_m *Service) Unsubscribe(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, statusPage
func (_m *Service) Update(ctx context.Context, statusPage *entities.StatusPage) error {
	ret := _m.Called(ctx, statusPage)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.StatusPage) error); ok {
		r0 = rf(ctx, statusPage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifySubscriber provides a mock function with given fields: ctx, token
func (_m *Service) VerifySubscriber(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifySubscriber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
