// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *Cache) DeleteUser(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserByEmail provides a mock function with given fields: ctx, email
func (_m *Cache) DeleteUserByEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *Cache) GetUser(ctx context.Context, userID uint) (*entities.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Cache) GetUserByEmail(ctx context.Context, email string) (*entities.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPasswordResetToken provides a mock function with given fields: ctx, userID, token, ttl
func (_m *Cache) SetPasswordResetToken(ctx context.Context, userID uint, token string, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetPasswordResetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, token, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUser provides a mock function with given fields: ctx, _a1, ttl
func (_m *Cache) SetUser(ctx context.Context, _a1 *entities.User, ttl time.Duration) error {
	ret := _m.Called(ctx, _a1, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User, time.Duration) error); ok {
		r0 = rf(ctx, _a1, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetUserByEmail provides a mock function with given fields: ctx, _a1, ttl
func (_m *Cache) SetUserByEmail(ctx context.Context, _a1 *entities.User, ttl time.Duration) error {
	ret := _m.Called(ctx, _a1, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetUserByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User, time.Duration) error); ok {
		r0 = rf(ctx, _a1, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyAndDeletePasswordResetToken provides a mock function with given fields: ctx, token
func (_m *Cache) VerifyAndDeletePasswordResetToken(ctx context.Context, token string) (uint, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAndDeletePasswordResetToken")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
