// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	entities "github.com/opsway-io/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ChangePasswordWithOldPassword provides a mock function with given fields: ctx, userID, oldPassword, newPassword
func (_m *Service) ChangePasswordWithOldPassword(ctx context.Context, userID uint, oldPassword string, newPassword string) error {
	ret := _m.Called(ctx, userID, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePasswordWithOldPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, userID, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangePasswordWithResetToken provides a mock function with given fields: ctx, token, newPassword
func (_m *Service) ChangePasswordWithResetToken(ctx context.Context, token string, newPassword string) error {
	ret := _m.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePasswordWithResetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Service) Create(ctx context.Context, _a1 *entities.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAvatar provides a mock function with given fields: ctx, userID
func (_m *Service) DeleteAvatar(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAvatarURLByID provides a mock function with given fields: userID
func (_m *Service) GetAvatarURLByID(userID uint) string {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarURLByID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUserAndTeamsByEmailAddress provides a mock function with given fields: ctx, email
func (_m *Service) GetUserAndTeamsByEmailAddress(ctx context.Context, email string) (*entities.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAndTeamsByEmailAddress")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAndTeamsByUserID provides a mock function with given fields: ctx, userId
func (_m *Service) GetUserAndTeamsByUserID(ctx context.Context, userId uint) (*entities.User, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAndTeamsByUserID")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.User, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.User); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *Service) GetUserByID(ctx context.Context, id uint) (*entities.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entities.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestPasswordReset provides a mock function with given fields: ctx, userId
func (_m *Service) RequestPasswordReset(ctx context.Context, userId uint) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAvatarFromURL provides a mock function with given fields: ctx, userID, URL
func (_m *Service) SetAvatarFromURL(ctx context.Context, userID uint, URL string) error {
	ret := _m.Called(ctx, userID, URL)

	if len(ret) == 0 {
		panic("no return value specified for SetAvatarFromURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, userID, URL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Service) Update(ctx context.Context, _a1 *entities.User) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadAvatar provides a mock function with given fields: ctx, userID, file
func (_m *Service) UploadAvatar(ctx context.Context, userID uint, file io.Reader) error {
	ret := _m.Called(ctx, userID, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, io.Reader) error); ok {
		r0 = rf(ctx, userID, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
