// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	http "github.com/opsway-io/backend/internal/probes/http"
	asserter "github.com/opsway-io/backend/internal/probes/http/asserter"

	mock "github.com/stretchr/testify/mock"
)

// Asserter is an autogenerated mock type for the Asserter type
type Asserter struct {
	mock.Mock
}

// Assert provides a mock function with given fields: result, rules
func (_m *Asserter) Assert(result *http.Result, rules []asserter.Rule) ([]bool, error) {
	ret := _m.Called(result, rules)

	if len(ret) == 0 {
		panic("no return value specified for Assert")
	}

	var r0 []bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Result, []asserter.Rule) ([]bool, error)); ok {
		return rf(result, rules)
	}
	if rf, ok := ret.Get(0).(func(*http.Result, []asserter.Rule) []bool); ok {
		r0 = rf(result, rules)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Result, []asserter.Rule) error); ok {
		r1 = rf(result, rules)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsRuleValid provides a mock function with given fields: rule
func (_m *Asserter) IsRuleValid(rule asserter.Rule) error {
	ret := _m.Called(rule)

	if len(ret) == 0 {
		panic("no return value specified for IsRuleValid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(asserter.Rule) error); ok {
		r0 = rf(rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAsserter creates a new instance of Asserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAsserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Asserter {
	mock := &Asserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
