// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	handlers "github.com/opsway-io/backend/internal/rest/handlers"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticatedHandlerFunc is an autogenerated mock type for the AuthenticatedHandlerFunc type
type AuthenticatedHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: c
func (_m *AuthenticatedHandlerFunc) Execute(c handlers.AuthenticatedContext) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(handlers.AuthenticatedContext) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthenticatedHandlerFunc creates a new instance of AuthenticatedHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticatedHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthenticatedHandlerFunc {
	mock := &AuthenticatedHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
