// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// DeleteTeam provides a mock function with given fields: ctx, teamID
func (_m *Cache) DeleteTeam(ctx context.Context, teamID uint) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTeamUserCount provides a mock function with given fields: ctx, teamID
func (_m *Cache) DeleteTeamUserCount(ctx context.Context, teamID uint) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeamUserCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTeam provides a mock function with given fields: ctx, teamID
func (_m *Cache) GetTeam(ctx context.Context, teamID uint) (*entities.Team, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Team, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Team); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamUserCount provides a mock function with given fields: ctx, teamID
func (_m *Cache) GetTeamUserCount(ctx context.Context, teamID uint) (int64, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamUserCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTeam provides a mock function with given fields: ctx, _a1, ttl
func (_m *Cache) SetTeam(ctx context.Context, _a1 *entities.Team, ttl time.Duration) error {
	ret := _m.Called(ctx, _a1, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Team, time.Duration) error); ok {
		r0 = rf(ctx, _a1, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTeamUserCount provides a mock function with given fields: ctx, teamID, count, ttl
func (_m *Cache) SetTeamUserCount(ctx context.Context, teamID uint, count int64, ttl time.Duration) error {
	ret := _m.Called(ctx, teamID, count, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetTeamUserCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int64, time.Duration) error); ok {
		r0 = rf(ctx, teamID, count, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
