// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// CookieService is an autogenerated mock type for the CookieService type
type CookieService struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: c
func (_m *CookieService) GetAccessToken(c echo.Context) (*http.Cookie, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessToken")
	}

	var r0 *http.Cookie
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) (*http.Cookie, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) *http.Cookie); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Cookie)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefreshToken provides a mock function with given fields: c
func (_m *CookieService) GetRefreshToken(c echo.Context) (*http.Cookie, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *http.Cookie
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context) (*http.Cookie, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(echo.Context) *http.Cookie); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Cookie)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAccessToken provides a mock function with given fields: c, value
func (_m *CookieService) SetAccessToken(c echo.Context, value string) error {
	ret := _m.Called(c, value)

	if len(ret) == 0 {
		panic("no return value specified for SetAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) error); ok {
		r0 = rf(c, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetRefreshToken provides a mock function with given fields: c, value
func (_m *CookieService) SetRefreshToken(c echo.Context, value string) error {
	ret := _m.Called(c, value)

	if len(ret) == 0 {
		panic("no return value specified for SetRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) error); ok {
		r0 = rf(c, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCookieService creates a new instance of CookieService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCookieService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CookieService {
	mock := &CookieService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
