// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *Repository) Create(ctx context.Context, _a1 *entities.Maintenance) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Maintenance) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *Repository) Delete(ctx context.Context, _a1 *entities.Maintenance) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Maintenance) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActive provides a mock function with given fields: ctx, now
func (_m *Repository) GetActive(ctx context.Context, now time.Time) (*[]entities.Maintenance, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 *[]entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*[]entities.Maintenance, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *[]entities.Maintenance); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveByMonitorIDs provides a mock function with given fields: ctx, now, monitorIDs
func (_m *Repository) GetActiveByMonitorIDs(ctx context.Context, now time.Time, monitorIDs []uint) ([]entities.Maintenance, error) {
	ret := _m.Called(ctx, now, monitorIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByMonitorIDs")
	}

	var r0 []entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, []uint) ([]entities.Maintenance, error)); ok {
		return rf(ctx, now, monitorIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, []uint) []entities.Maintenance); ok {
		r0 = rf(ctx, now, monitorIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, []uint) error); ok {
		r1 = rf(ctx, now, monitorIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByMonitorIDs provides a mock function with given fields: ctx, monitorIDs
func (_m *Repository) GetAllByMonitorIDs(ctx context.Context, monitorIDs []uint) ([]entities.Maintenance, error) {
	ret := _m.Called(ctx, monitorIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByMonitorIDs")
	}

	var r0 []entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]entities.Maintenance, error)); ok {
		return rf(ctx, monitorIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []entities.Maintenance); ok {
		r0 = rf(ctx, monitorIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, monitorIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id uint) (*entities.Maintenance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Maintenance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Maintenance); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeamID provides a mock function with given fields: ctx, teamID
func (_m *Repository) GetByTeamID(ctx context.Context, teamID uint) (*[]entities.Maintenance, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamID")
	}

	var r0 *[]entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*[]entities.Maintenance, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *[]entities.Maintenance); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnnotified provides a mock function with given fields: ctx, now
func (_m *Repository) GetUnnotified(ctx context.Context, now time.Time) (*[]entities.Maintenance, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for GetUnnotified")
	}

	var r0 *[]entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (*[]entities.Maintenance, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) *[]entities.Maintenance); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUpcomingByMonitorIDs provides a mock function with given fields: ctx, now, monitorIDs
func (_m *Repository) GetUpcomingByMonitorIDs(ctx context.Context, now time.Time, monitorIDs []uint) ([]entities.Maintenance, error) {
	ret := _m.Called(ctx, now, monitorIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetUpcomingByMonitorIDs")
	}

	var r0 []entities.Maintenance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, []uint) ([]entities.Maintenance, error)); ok {
		return rf(ctx, now, monitorIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, []uint) []entities.Maintenance); ok {
		r0 = rf(ctx, now, monitorIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Maintenance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, []uint) error); ok {
		r1 = rf(ctx, now, monitorIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Repository) Update(ctx context.Context, _a1 *entities.Maintenance) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Maintenance) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
