// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// Seeder is an autogenerated mock type for the Seeder type
type Seeder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: db
func (_m *Seeder) Execute(db *gorm.DB) {
	_m.Called(db)
}

// NewSeeder creates a new instance of Seeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Seeder {
	mock := &Seeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
