// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	billing "github.com/opsway-io/backend/internal/billing"
	entities "github.com/opsway-io/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"

	product "github.com/stripe/stripe-go/v81/product"

	session "github.com/stripe/stripe-go/v81/checkout/session"

	stripe "github.com/stripe/stripe-go/v81"

	subscription "github.com/stripe/stripe-go/v81/subscription"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CancelSubscribtion provides a mock function with given fields: team
func (_m *Service) CancelSubscribtion(team *entities.Team) (*stripe.Subscription, error) {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for CancelSubscribtion")
	}

	var r0 *stripe.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Team) (*stripe.Subscription, error)); ok {
		return rf(team)
	}
	if rf, ok := ret.Get(0).(func(*entities.Team) *stripe.Subscription); ok {
		r0 = rf(team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Team) error); ok {
		r1 = rf(team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConstructEvent provides a mock function with given fields: payload, header
func (_m *Service) ConstructEvent(payload []byte, header string) (stripe.Event, error) {
	ret := _m.Called(payload, header)

	if len(ret) == 0 {
		panic("no return value specified for ConstructEvent")
	}

	var r0 stripe.Event
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string) (stripe.Event, error)); ok {
		return rf(payload, header)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) stripe.Event); ok {
		r0 = rf(payload, header)
	} else {
		r0 = ret.Get(0).(stripe.Event)
	}

	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(payload, header)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCheckoutSession provides a mock function with given fields: team, priceID
func (_m *Service) CreateCheckoutSession(team *entities.Team, priceID string) (*stripe.CheckoutSession, error) {
	ret := _m.Called(team, priceID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 *stripe.CheckoutSession
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Team, string) (*stripe.CheckoutSession, error)); ok {
		return rf(team, priceID)
	}
	if rf, ok := ret.Get(0).(func(*entities.Team, string) *stripe.CheckoutSession); ok {
		r0 = rf(team, priceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.CheckoutSession)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Team, string) error); ok {
		r1 = rf(team, priceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCustomerPortal provides a mock function with given fields: team
func (_m *Service) CreateCustomerPortal(team *entities.Team) (*stripe.BillingPortalSession, error) {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomerPortal")
	}

	var r0 *stripe.BillingPortalSession
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Team) (*stripe.BillingPortalSession, error)); ok {
		return rf(team)
	}
	if rf, ok := ret.Get(0).(func(*entities.Team) *stripe.BillingPortalSession); ok {
		r0 = rf(team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.BillingPortalSession)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Team) error); ok {
		r1 = rf(team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBillingPortal provides a mock function with given fields: team
func (_m *Service) GetBillingPortal(team *entities.Team) (*stripe.BillingPortalConfiguration, error) {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for GetBillingPortal")
	}

	var r0 *stripe.BillingPortalConfiguration
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Team) (*stripe.BillingPortalConfiguration, error)); ok {
		return rf(team)
	}
	if rf, ok := ret.Get(0).(func(*entities.Team) *stripe.BillingPortalConfiguration); ok {
		r0 = rf(team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.BillingPortalConfiguration)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Team) error); ok {
		r1 = rf(team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckoutSession provides a mock function with given fields: sessionID
func (_m *Service) GetCheckoutSession(sessionID string) (*stripe.CheckoutSession, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSession")
	}

	var r0 *stripe.CheckoutSession
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*stripe.CheckoutSession, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) *stripe.CheckoutSession); ok {
		r0 = rf(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.CheckoutSession)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerSession provides a mock function with given fields: team
func (_m *Service) GetCustomerSession(team *entities.Team) (*stripe.CustomerSession, error) {
	ret := _m.Called(team)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerSession")
	}

	var r0 *stripe.CustomerSession
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Team) (*stripe.CustomerSession, error)); ok {
		return rf(team)
	}
	if rf, ok := ret.Get(0).(func(*entities.Team) *stripe.CustomerSession); ok {
		r0 = rf(team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.CustomerSession)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Team) error); ok {
		r1 = rf(team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerSubscribtion provides a mock function with given fields: customerID
func (_m *Service) GetCustomerSubscribtion(customerID string) *subscription.Iter {
	ret := _m.Called(customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerSubscribtion")
	}

	var r0 *subscription.Iter
	if rf, ok := ret.Get(0).(func(string) *subscription.Iter); ok {
		r0 = rf(customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscription.Iter)
		}
	}

	return r0
}

// GetLineItems provides a mock function with given fields: sessionID
func (_m *Service) GetLineItems(sessionID string) *session.LineItemIter {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetLineItems")
	}

	var r0 *session.LineItemIter
	if rf, ok := ret.Get(0).(func(string) *session.LineItemIter); ok {
		r0 = rf(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.LineItemIter)
		}
	}

	return r0
}

// GetPrices provides a mock function with given fields: priceLookupKeys
func (_m *Service) GetPrices(priceLookupKeys []string) ([]*stripe.Price, error) {
	ret := _m.Called(priceLookupKeys)

	if len(ret) == 0 {
		panic("no return value specified for GetPrices")
	}

	var r0 []*stripe.Price
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]*stripe.Price, error)); ok {
		return rf(priceLookupKeys)
	}
	if rf, ok := ret.Get(0).(func([]string) []*stripe.Price); ok {
		r0 = rf(priceLookupKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*stripe.Price)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(priceLookupKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: productID
func (_m *Service) GetProduct(productID string) (*stripe.Product, error) {
	ret := _m.Called(productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *stripe.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*stripe.Product, error)); ok {
		return rf(productID)
	}
	if rf, ok := ret.Get(0).(func(string) *stripe.Product); ok {
		r0 = rf(productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with no fields
func (_m *Service) GetProducts() *product.Iter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 *product.Iter
	if rf, ok := ret.Get(0).(func() *product.Iter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Iter)
		}
	}

	return r0
}

// GetSubscribtion provides a mock function with given fields: subID
func (_m *Service) GetSubscribtion(subID string) (*stripe.Subscription, error) {
	ret := _m.Called(subID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscribtion")
	}

	var r0 *stripe.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*stripe.Subscription, error)); ok {
		return rf(subID)
	}
	if rf, ok := ret.Get(0).(func(string) *stripe.Subscription); ok {
		r0 = rf(subID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(subID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostConfig provides a mock function with no fields
func (_m *Service) PostConfig() billing.StripeConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PostConfig")
	}

	var r0 billing.StripeConfig
	if rf, ok := ret.Get(0).(func() billing.StripeConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(billing.StripeConfig)
	}

	return r0
}

// UpdateSubscribtion provides a mock function with given fields: team, priceID
func (_m *Service) UpdateSubscribtion(team *entities.Team, priceID string) (*stripe.Subscription, error) {
	ret := _m.Called(team, priceID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscribtion")
	}

	var r0 *stripe.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Team, string) (*stripe.Subscription, error)); ok {
		return rf(team, priceID)
	}
	if rf, ok := ret.Get(0).(func(*entities.Team, string) *stripe.Subscription); ok {
		r0 = rf(team, priceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Team, string) error); ok {
		r1 = rf(team, priceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
