// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RCAWorker is an autogenerated mock type for the RCAWorker type
type RCAWorker struct {
	mock.Mock
}

// Start provides a mock function with given fields: ctx
func (_m *RCAWorker) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRCAWorker creates a new instance of RCAWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRCAWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *RCAWorker {
	mock := &RCAWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
