// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"
	incident "github.com/opsway-io/backend/internal/incident"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, incidents
func (_m *Repository) Create(ctx context.Context, incidents *[]entities.Incident) error {
	ret := _m.Called(ctx, incidents)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *[]entities.Incident) error); ok {
		r0 = rf(ctx, incidents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *Repository) Delete(ctx context.Context, _a1 *entities.Incident) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Incident) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id uint) (*entities.Incident, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Incident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Incident, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Incident); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByMonitorIDWithAssertionPaginated provides a mock function with given fields: ctx, monitorID, offset, limit
func (_m *Repository) GetByMonitorIDWithAssertionPaginated(ctx context.Context, monitorID uint, offset *int, limit *int) (*[]incident.IncidentAndAssertion, error) {
	ret := _m.Called(ctx, monitorID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByMonitorIDWithAssertionPaginated")
	}

	var r0 *[]incident.IncidentAndAssertion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int) (*[]incident.IncidentAndAssertion, error)); ok {
		return rf(ctx, monitorID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int) *[]incident.IncidentAndAssertion); ok {
		r0 = rf(ctx, monitorID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]incident.IncidentAndAssertion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *int, *int) error); ok {
		r1 = rf(ctx, monitorID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeamIDMonitorsIncidentStats provides a mock function with given fields: ctx, teamID, start, end
func (_m *Repository) GetByTeamIDMonitorsIncidentStats(ctx context.Context, teamID uint, start string, end string) (*[]entities.MonitorIncident, error) {
	ret := _m.Called(ctx, teamID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamIDMonitorsIncidentStats")
	}

	var r0 *[]entities.MonitorIncident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) (*[]entities.MonitorIncident, error)); ok {
		return rf(ctx, teamID, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) *[]entities.MonitorIncident); ok {
		r0 = rf(ctx, teamID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.MonitorIncident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, string) error); ok {
		r1 = rf(ctx, teamID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeamIDPaginated provides a mock function with given fields: ctx, teamID, offset, limit
func (_m *Repository) GetByTeamIDPaginated(ctx context.Context, teamID uint, offset *int, limit *int) (*[]entities.Incident, error) {
	ret := _m.Called(ctx, teamID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeamIDPaginated")
	}

	var r0 *[]entities.Incident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int) (*[]entities.Incident, error)); ok {
		return rf(ctx, teamID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int) *[]entities.Incident); ok {
		r0 = rf(ctx, teamID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *int, *int) error); ok {
		r1 = rf(ctx, teamID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Repository) Update(ctx context.Context, _a1 *entities.Incident) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Incident) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, incidents
func (_m *Repository) Upsert(ctx context.Context, incidents *[]entities.Incident) error {
	ret := _m.Called(ctx, incidents)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *[]entities.Incident) error); ok {
		r0 = rf(ctx, incidents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByMonitorIDs provides a mock function with given fields: ctx, monitorIDs
func (_m *Repository) GetActiveByMonitorIDs(ctx context.Context, monitorIDs []uint) ([]entities.Incident, error) {
	ret := _m.Called(ctx, monitorIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByMonitorIDs")
	}

	var r0 []entities.Incident
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) ([]entities.Incident, error)); ok {
		return rf(ctx, monitorIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint) []entities.Incident); ok {
		r0 = rf(ctx, monitorIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Incident)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint) error); ok {
		r1 = rf(ctx, monitorIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
