// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteIngress provides a mock function with given fields: ctx, domain
func (_m *Service) DeleteIngress(ctx context.Context, domain string) error {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertIngress provides a mock function with given fields: ctx, domain
func (_m *Service) UpsertIngress(ctx context.Context, domain string) error {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for UpsertIngress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
