// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/opsway-io/backend/internal/event/events"

	message "github.com/ThreeDotsLabs/watermill/message"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Publish provides a mock function with given fields: _a0
func (_m *Service) Publish(_a0 events.Event) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(events.Event) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, eventName
func (_m *Service) Subscribe(ctx context.Context, eventName string) (<-chan *message.Message, error) {
	ret := _m.Called(ctx, eventName)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan *message.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan *message.Message, error)); ok {
		return rf(ctx, eventName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan *message.Message); ok {
		r0 = rf(ctx, eventName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *message.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
