// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreatePolicy provides a mock function with given fields: ctx, policy
func (_m *Repository) CreatePolicy(ctx context.Context, policy *entities.EscalationPolicy) error {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for CreatePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.EscalationPolicy) error); ok {
		r0 = rf(ctx, policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPolicyByTeamID provides a mock function with given fields: ctx, teamID
func (_m *Repository) GetPolicyByTeamID(ctx context.Context, teamID uint) (*entities.EscalationPolicy, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicyByTeamID")
	}

	var r0 *entities.EscalationPolicy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.EscalationPolicy, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.EscalationPolicy); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.EscalationPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRotationsByPolicyID provides a mock function with given fields: ctx, policyID
func (_m *Repository) GetRotationsByPolicyID(ctx context.Context, policyID uint) ([]entities.OnCallRotation, error) {
	ret := _m.Called(ctx, policyID)

	if len(ret) == 0 {
		panic("no return value specified for GetRotationsByPolicyID")
	}

	var r0 []entities.OnCallRotation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]entities.OnCallRotation, error)); ok {
		return rf(ctx, policyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.OnCallRotation); ok {
		r0 = rf(ctx, policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.OnCallRotation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, policyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRotationsByPolicyIDAndTier provides a mock function with given fields: ctx, policyID, tier
func (_m *Repository) GetRotationsByPolicyIDAndTier(ctx context.Context, policyID uint, tier int) ([]entities.OnCallRotation, error) {
	ret := _m.Called(ctx, policyID, tier)

	if len(ret) == 0 {
		panic("no return value specified for GetRotationsByPolicyIDAndTier")
	}

	var r0 []entities.OnCallRotation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) ([]entities.OnCallRotation, error)); ok {
		return rf(ctx, policyID, tier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, int) []entities.OnCallRotation); ok {
		r0 = rf(ctx, policyID, tier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.OnCallRotation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, int) error); ok {
		r1 = rf(ctx, policyID, tier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetRotations provides a mock function with given fields: ctx, policyID, rotations
func (_m *Repository) SetRotations(ctx context.Context, policyID uint, rotations []entities.OnCallRotation) error {
	ret := _m.Called(ctx, policyID, rotations)

	if len(ret) == 0 {
		panic("no return value specified for SetRotations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []entities.OnCallRotation) error); ok {
		r0 = rf(ctx, policyID, rotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePolicy provides a mock function with given fields: ctx, policy
func (_m *Repository) UpdatePolicy(ctx context.Context, policy *entities.EscalationPolicy) error {
	ret := _m.Called(ctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.EscalationPolicy) error); ok {
		r0 = rf(ctx, policy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
