// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteFile provides a mock function with given fields: ctx, bucket, key
func (_m *Service) DeleteFile(ctx context.Context, bucket string, key string) error {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPublicFileURL provides a mock function with given fields: bucket, key
func (_m *Service) GetPublicFileURL(bucket string, key string) string {
	ret := _m.Called(bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicFileURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(bucket, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PutFile provides a mock function with given fields: ctx, bucket, key, data
func (_m *Service) PutFile(ctx context.Context, bucket string, key string, data io.Reader) error {
	ret := _m.Called(ctx, bucket, key, data)

	if len(ret) == 0 {
		panic("no return value specified for PutFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) error); ok {
		r0 = rf(ctx, bucket, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
