openapi: "3.0.0"

info:
  title: Opsway API
  version: 1.0.0

servers:
  - url: https://opsway.io/api/v1
  - url: "{scheme}://{host}"
    description: Custom
    variables:
      scheme:
        default: "http"
        enum:
          - "http"
          - "https"
      host:
        default: "localhost:8080/v1"

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        logo:
          type: string
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    Account:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        displayName:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    Monitor:
      type: integer
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

paths:
  # Authentication
  /authentication/login:
    post:
      tags:
        - Authentication
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    readOnly: true
                  user:
                    $ref: "#/components/schemas/User"
                    readOnly: true
        401:
          description: Unauthorized
  # User
  /users/{userId}:
    get:
      tags:
        - Users
      summary: Get user
      security:
        - JWT: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
        404:
          description: Not found
    put:
      tags:
        - Users
      summary: Update user
      security:
        - JWT: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        204:
          description: OK
        400:
          description: Bad request
        401:
          description: Unauthorized
        404:
          description: Not found

  # Teams
  /teams/{teamId}:
    get:
      tags:
        - Teams
      summary: Get team
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
        401:
          description: Unauthorized
        404:
          description: Not found
    put:
      tags:
        - Teams
      summary: Update team
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Team"
      responses:
        204:
          description: OK
        400:
          description: Bad request
        401:
          description: Unauthorized
        404:
          description: Not found

  # Users
  /teams/{teamId}/users:
    get:
      tags:
        - Teams
      summary: Get team users
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        401:
          description: Unauthorized
        404:
          description: Not found

  # Monitors
  /teams/{teamId}/monitors:
    get:
      tags:
        - Monitors
      summary: Get team monitors
      security:
        - JWT: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Monitor"
        401:
          description: Unauthorized
        404:
          description: Not found
  /teams/{teamId}/monitors/{monitorId}:
    get:
      tags:
        - Monitors
      summary: Get team monitor
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
        - name: monitorId
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Monitor"
        404:
          description: Not found
        401:
          description: Unauthorized
    post:
      tags:
        - Monitors
      summary: Create team monitor
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
        - name: monitorId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Monitor"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Monitor"
        400:
          description: Bad request
        401:
          description: Unauthorized
        404:
          description: Not found
    put:
      tags:
        - Monitors
      summary: Update team monitor
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
        - name: monitorId
          in: path
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Monitor"
      responses:
        204:
          description: OK
        400:
          description: Bad request
        401:
          description: Unauthorized
        404:
          description: Not found
    delete:
      tags:
        - Monitors
      summary: Delete team monitor
      security:
        - JWT: []
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: number
        - name: monitorId
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Monitor"
        401:
          description: Unauthorized
        404:
          description: Not found
