// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/opsway-io/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"

	team "github.com/opsway-io/backend/internal/team"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, teamID, userID, role
func (_m *Repository) AddUser(ctx context.Context, teamID uint, userID uint, role entities.TeamRole) error {
	ret := _m.Called(ctx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, entities.TeamRole) error); ok {
		r0 = rf(ctx, teamID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTeamInvitation provides a mock function with given fields: ctx, invitation
func (_m *Repository) CreateTeamInvitation(ctx context.Context, invitation *entities.TeamInvitation) error {
	ret := _m.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeamInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.TeamInvitation) error); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWithOwnerUserID provides a mock function with given fields: ctx, _a1, ownerUserID
func (_m *Repository) CreateWithOwnerUserID(ctx context.Context, _a1 *entities.Team, ownerUserID uint) error {
	ret := _m.Called(ctx, _a1, ownerUserID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOwnerUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Team, uint) error); ok {
		r0 = rf(ctx, _a1, ownerUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTeamInvitation provides a mock function with given fields: ctx, teamID, email
func (_m *Repository) DeleteTeamInvitation(ctx context.Context, teamID uint, email string) error {
	ret := _m.Called(ctx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeamInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, teamID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, teamId
func (_m *Repository) GetByID(ctx context.Context, teamId uint) (*entities.Team, error) {
	ret := _m.Called(ctx, teamId)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Team, error)); ok {
		return rf(ctx, teamId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Team); ok {
		r0 = rf(ctx, teamId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStripeID provides a mock function with given fields: ctx, stripeID
func (_m *Repository) GetByStripeID(ctx context.Context, stripeID string) (*entities.Team, error) {
	ret := _m.Called(ctx, stripeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStripeID")
	}

	var r0 *entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Team, error)); ok {
		return rf(ctx, stripeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Team); ok {
		r0 = rf(ctx, stripeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stripeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamInvitationByToken provides a mock function with given fields: ctx, token
func (_m *Repository) GetTeamInvitationByToken(ctx context.Context, token string) (*entities.TeamInvitation, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamInvitationByToken")
	}

	var r0 *entities.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.TeamInvitation, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.TeamInvitation); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamInvitations provides a mock function with given fields: ctx, teamID
func (_m *Repository) GetTeamInvitations(ctx context.Context, teamID uint) (*[]entities.TeamInvitation, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamInvitations")
	}

	var r0 *[]entities.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*[]entities.TeamInvitation, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *[]entities.TeamInvitation); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamUserCount provides a mock function with given fields: ctx, teamId
func (_m *Repository) GetTeamUserCount(ctx context.Context, teamId uint) (int64, error) {
	ret := _m.Called(ctx, teamId)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamUserCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, teamId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, teamId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamsAndRoleByUserID provides a mock function with given fields: ctx, userID
func (_m *Repository) GetTeamsAndRoleByUserID(ctx context.Context, userID uint) (*[]team.TeamAndRole, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamsAndRoleByUserID")
	}

	var r0 *[]team.TeamAndRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*[]team.TeamAndRole, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *[]team.TeamAndRole); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]team.TeamAndRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRole provides a mock function with given fields: ctx, teamID, userID
func (_m *Repository) GetUserRole(ctx context.Context, teamID uint, userID uint) (*entities.TeamRole, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRole")
	}

	var r0 *entities.TeamRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*entities.TeamRole, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entities.TeamRole); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TeamRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByID provides a mock function with given fields: ctx, teamId, offset, limit, query, role
func (_m *Repository) GetUsersByID(ctx context.Context, teamId uint, offset *int, limit *int, query *string, role *entities.TeamRole) (*[]team.TeamUser, error) {
	ret := _m.Called(ctx, teamId, offset, limit, query, role)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByID")
	}

	var r0 *[]team.TeamUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int, *string, *entities.TeamRole) (*[]team.TeamUser, error)); ok {
		return rf(ctx, teamId, offset, limit, query, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int, *string, *entities.TeamRole) *[]team.TeamUser); ok {
		r0 = rf(ctx, teamId, offset, limit, query, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]team.TeamUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *int, *int, *string, *entities.TeamRole) error); ok {
		r1 = rf(ctx, teamId, offset, limit, query, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsNameAvailable provides a mock function with given fields: ctx, name
func (_m *Repository) IsNameAvailable(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsNameAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsUserOnTeamByEmail provides a mock function with given fields: ctx, teamID, email
func (_m *Repository) IsUserOnTeamByEmail(ctx context.Context, teamID uint, email string) (bool, error) {
	ret := _m.Called(ctx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for IsUserOnTeamByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) (bool, error)); ok {
		return rf(ctx, teamID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) bool); ok {
		r0 = rf(ctx, teamID, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, teamID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveUser provides a mock function with given fields: ctx, teamID, userID
func (_m *Repository) RemoveUser(ctx context.Context, teamID uint, userID uint) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *Repository) Update(ctx context.Context, _a1 *entities.Team) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Team) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBilling provides a mock function with given fields: ctx, teamID, customerID, plan
func (_m *Repository) UpdateBilling(ctx context.Context, teamID uint, customerID string, plan string) error {
	ret := _m.Called(ctx, teamID, customerID, plan)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBilling")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, teamID, customerID, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDisplayName provides a mock function with given fields: ctx, teamID, displayName
func (_m *Repository) UpdateDisplayName(ctx context.Context, teamID uint, displayName string) error {
	ret := _m.Called(ctx, teamID, displayName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDisplayName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, teamID, displayName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTeam provides a mock function with given fields: ctx, _a1
func (_m *Repository) UpdateTeam(ctx context.Context, _a1 *entities.Team) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Team) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserRole provides a mock function with given fields: ctx, teamID, userID, role
func (_m *Repository) UpdateUserRole(ctx context.Context, teamID uint, userID uint, role entities.TeamRole) error {
	ret := _m.Called(ctx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, entities.TeamRole) error); ok {
		r0 = rf(ctx, teamID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
