// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	entities "github.com/opsway-io/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"

	team "github.com/opsway-io/backend/internal/team"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AcceptInviteByToken provides a mock function with given fields: ctx, token, user
func (_m *Service) AcceptInviteByToken(ctx context.Context, token string, user *entities.User) error {
	ret := _m.Called(ctx, token, user)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInviteByToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.User) error); ok {
		r0 = rf(ctx, token, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWithOwnerUserID provides a mock function with given fields: ctx, _a1, ownerUserID
func (_m *Service) CreateWithOwnerUserID(ctx context.Context, _a1 *entities.Team, ownerUserID uint) error {
	ret := _m.Called(ctx, _a1, ownerUserID)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithOwnerUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Team, uint) error); ok {
		r0 = rf(ctx, _a1, ownerUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Service) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAvatar provides a mock function with given fields: ctx, teamID
func (_m *Service) DeleteAvatar(ctx context.Context, teamID uint) error {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, teamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTeamInvitation provides a mock function with given fields: ctx, teamID, email
func (_m *Service) DeleteTeamInvitation(ctx context.Context, teamID uint, email string) error {
	ret := _m.Called(ctx, teamID, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTeamInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, teamID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateInviteLink provides a mock function with given fields: ctx, teamID, role, email
func (_m *Service) GenerateInviteLink(ctx context.Context, teamID uint, role entities.TeamRole, email string) (string, error) {
	ret := _m.Called(ctx, teamID, role, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateInviteLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, entities.TeamRole, string) (string, error)); ok {
		return rf(ctx, teamID, role, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, entities.TeamRole, string) string); ok {
		r0 = rf(ctx, teamID, role, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, entities.TeamRole, string) error); ok {
		r1 = rf(ctx, teamID, role, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvatarURLByID provides a mock function with given fields: teamID
func (_m *Service) GetAvatarURLByID(teamID uint) string {
	ret := _m.Called(teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvatarURLByID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(teamID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, teamId
func (_m *Service) GetByID(ctx context.Context, teamId uint) (*entities.Team, error) {
	ret := _m.Called(ctx, teamId)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entities.Team, error)); ok {
		return rf(ctx, teamId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entities.Team); ok {
		r0 = rf(ctx, teamId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStripeID provides a mock function with given fields: ctx, stripeID
func (_m *Service) GetByStripeID(ctx context.Context, stripeID string) (*entities.Team, error) {
	ret := _m.Called(ctx, stripeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStripeID")
	}

	var r0 *entities.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Team, error)); ok {
		return rf(ctx, stripeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Team); ok {
		r0 = rf(ctx, stripeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stripeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamInvitations provides a mock function with given fields: ctx, teamID
func (_m *Service) GetTeamInvitations(ctx context.Context, teamID uint) (*[]entities.TeamInvitation, error) {
	ret := _m.Called(ctx, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamInvitations")
	}

	var r0 *[]entities.TeamInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*[]entities.TeamInvitation, error)); ok {
		return rf(ctx, teamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *[]entities.TeamInvitation); ok {
		r0 = rf(ctx, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.TeamInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamUserCount provides a mock function with given fields: ctx, teamId
func (_m *Service) GetTeamUserCount(ctx context.Context, teamId uint) (int64, error) {
	ret := _m.Called(ctx, teamId)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamUserCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, teamId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, teamId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, teamId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeamsAndRoleByUserID provides a mock function with given fields: ctx, userID
func (_m *Service) GetTeamsAndRoleByUserID(ctx context.Context, userID uint) (*[]team.TeamAndRole, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamsAndRoleByUserID")
	}

	var r0 *[]team.TeamAndRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*[]team.TeamAndRole, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *[]team.TeamAndRole); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]team.TeamAndRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRole provides a mock function with given fields: ctx, teamID, userID
func (_m *Service) GetUserRole(ctx context.Context, teamID uint, userID uint) (*entities.TeamRole, error) {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRole")
	}

	var r0 *entities.TeamRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) (*entities.TeamRole, error)); ok {
		return rf(ctx, teamID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) *entities.TeamRole); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TeamRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = rf(ctx, teamID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersByID provides a mock function with given fields: ctx, teamId, offset, limit, query, role
func (_m *Service) GetUsersByID(ctx context.Context, teamId uint, offset *int, limit *int, query *string, role *entities.TeamRole) (*[]team.TeamUser, error) {
	ret := _m.Called(ctx, teamId, offset, limit, query, role)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByID")
	}

	var r0 *[]team.TeamUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int, *string, *entities.TeamRole) (*[]team.TeamUser, error)); ok {
		return rf(ctx, teamId, offset, limit, query, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *int, *int, *string, *entities.TeamRole) *[]team.TeamUser); ok {
		r0 = rf(ctx, teamId, offset, limit, query, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]team.TeamUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *int, *int, *string, *entities.TeamRole) error); ok {
		r1 = rf(ctx, teamId, offset, limit, query, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InviteByEmail provides a mock function with given fields: ctx, teamID, role, email
func (_m *Service) InviteByEmail(ctx context.Context, teamID uint, role entities.TeamRole, email string) error {
	ret := _m.Called(ctx, teamID, role, email)

	if len(ret) == 0 {
		panic("no return value specified for InviteByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, entities.TeamRole, string) error); ok {
		r0 = rf(ctx, teamID, role, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsNameAvailable provides a mock function with given fields: ctx, name
func (_m *Service) IsNameAvailable(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsNameAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveUser provides a mock function with given fields: ctx, teamID, userID
func (_m *Service) RemoveUser(ctx context.Context, teamID uint, userID uint) error {
	ret := _m.Called(ctx, teamID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, teamID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBilling provides a mock function with given fields: ctx, teamID, customerID, plan
func (_m *Service) UpdateBilling(ctx context.Context, teamID uint, customerID string, plan string) error {
	ret := _m.Called(ctx, teamID, customerID, plan)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBilling")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, teamID, customerID, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDisplayName provides a mock function with given fields: ctx, teamID, displayName
func (_m *Service) UpdateDisplayName(ctx context.Context, teamID uint, displayName string) error {
	ret := _m.Called(ctx, teamID, displayName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDisplayName")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, teamID, displayName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTeam provides a mock function with given fields: ctx, _a1
func (_m *Service) UpdateTeam(ctx context.Context, _a1 *entities.Team) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTeam")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Team) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserRole provides a mock function with given fields: ctx, teamID, userID, role
func (_m *Service) UpdateUserRole(ctx context.Context, teamID uint, userID uint, role entities.TeamRole) error {
	ret := _m.Called(ctx, teamID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, entities.TeamRole) error); ok {
		r0 = rf(ctx, teamID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadAvatar provides a mock function with given fields: ctx, teamID, file
func (_m *Service) UploadAvatar(ctx context.Context, teamID uint, file io.Reader) error {
	ret := _m.Called(ctx, teamID, file)

	if len(ret) == 0 {
		panic("no return value specified for UploadAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, io.Reader) error); ok {
		r0 = rf(ctx, teamID, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
