name: Golang

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Test
        run: go test -v ./...
