name: OpenAPI Linting

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  yaml:
    name: YAML
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Lint all the yaml files
        uses: mikefarah/yq@master
        with:
          cmd: yq . ./docs/*.yaml

  spellcheck:
    name: Spellcheck
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check spelling of files
        uses: crate-ci/typos@master
        with: 
          files: ./docs/*.yaml